### ISSUE TITLE
Compatibility with Oracle 11

### ISSUE THREAD

**Issue by niv0** [isisaddons-legacy/isis-module-security#34]
Default names of tables and foreign keys are incompatible with Oracle 11 - since some of them are longer then 30 characters.

This constraint can be solved by externalizing the package.jdo file and adaptin it, but in the e.g. ApplicationPermission class the index name is simply too long:

`@javax.jdo.annotations.Uniques({@javax.jdo.annotations.Unique(name = "ApplicationPermission_role_feature_rule_UNQ", members = {"role", "featureType", "featureFqn", "rule"})})`

In total there are 7 indexes with too long names.

**Comment by danhaywood** [comment]
please raise a PR, I'll be happy to merge it in.

**Comment by danhaywood** [comment]
moved to https://github.com/incodehq/incode-platform/issues/39
