### ISSUE TITLE
Allow self registered users to be linked to application tenancies

### ISSUE THREAD

**Issue by bibryam** [isisaddons-legacy/isis-module-security#45]
It would be nice if users were able to create application tenancies and invite/add users though the self registration process.

Currently, the self registered users don't belong to any tenancy, and they have to be added to a tenancy after their regitration.

**Comment by jcvanderwal** [comment]
This is imho the responsibility of the app that has the the module embedded. You could see if you can hook into a domain event after the user has been created?

**Comment by bibryam** [comment]
I have to investigate more this, but the fact that the user and tenancy entities belong into the addon, makes me think that the funcationality should be there OOTB too.
I'm think this more from SAAS point of view, where a person creates an account, then tenancy/organization and invite other users to join the platform. But these new users should belong to the tenancy automatically onces registered with the app. Something among these lines.

**Comment by danhaywood** [comment]
moved to https://github.com/incodehq/incode-platform/issues/43
