### ISSUE TITLE
Simplify SecurityModuleAppUserRegistrationServiceAbstract

### ISSUE THREAD

**Issue by bibryam** [isisaddons-legacy/isis-module-security#46]
What is the reason for SecurityModuleAppUserRegistrationServiceAbstract to have 2 abstract methods getInitialRole and getAdditionalInitialRoles?

Why not have only one method that returns Set<ApplicationRole>? It will be easier to override. Otherwise, it makes you think that initial role is different that any any additional role.?

**Comment by danhaywood** [comment]
Yep, I agree.  Was probably just how it evolved over time.

Obviously it'll be a breaking API change, but I'm less fussy about that so long as the changelog in the README explains how to fix (perhaps worth an additional section in the README to address this).

If you want to create a PR for this, I'll be happy to merge it in.

Thx

**Comment by danhaywood** [comment]
moved to https://github.com/incodehq/incode-platform/issues/44
